export const SET_CITY = 'SET_CITY';
export const SET_WEATHER = 'SET_WEATHER';
export const CHANGE_TEMP_SCALE = 'CHANGE_TEMP_SCALE';
export const SET_FORECAST = 'SET_FORECAST';
export const CHANGE_FORECAST_MODE = 'CHANGE_FORECAST_MODE';